# Generated by Django 2.0.4 on 2018-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('idauditoria', models.IntegerField(primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField()),
                ('tabla', models.CharField(max_length=255)),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('dataantigua', models.TextField()),
                ('datanueva', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idfoto', models.IntegerField(primary_key=True, serialize=False)),
                ('idmodulo', models.IntegerField()),
                ('ruta', models.CharField(max_length=255)),
                ('nombresinextension', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('nombrefoto', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historiainvernadero',
            fields=[
                ('idhistoriainvernadero', models.IntegerField(primary_key=True, serialize=False)),
                ('idinvernadero', models.IntegerField()),
                ('nivelenergia', models.FloatField()),
                ('niveltanqueagua', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historiamodulo',
            fields=[
                ('idhistoriamodulo', models.IntegerField(primary_key=True, serialize=False)),
                ('idmodulo', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('humedadtierra', models.FloatField()),
                ('humedadambiente', models.FloatField()),
                ('nivelagua', models.FloatField()),
                ('concentracionco2', models.FloatField()),
                ('luz', models.BooleanField()),
                ('fecharegistro', models.DateTimeField()),
                ('comentario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Historiaplanta',
            fields=[
                ('idhistoriaplanta', models.IntegerField(primary_key=True, serialize=False)),
                ('idplanta', models.IntegerField()),
                ('idzona', models.IntegerField()),
                ('humedad', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historiasemilla',
            fields=[
                ('idhistoriasemilla', models.IntegerField(primary_key=True, serialize=False)),
                ('idsemilla', models.IntegerField()),
                ('idmodulo', models.IntegerField()),
                ('posx', models.IntegerField()),
                ('posy', models.IntegerField()),
                ('comentario', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historiazona',
            fields=[
                ('idhistoriazona', models.IntegerField(primary_key=True, serialize=False)),
                ('idzona', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('ph', models.FloatField()),
                ('concentracionco2', models.FloatField()),
                ('fecharegistro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('idinvernadero', models.IntegerField(primary_key=True, serialize=False)),
                ('idadmin', models.IntegerField()),
                ('codigoinvernadero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField()),
                ('area', models.FloatField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulosemilla',
            fields=[
                ('idmodulo', models.IntegerField(primary_key=True, serialize=False)),
                ('codigomodulo', models.IntegerField(unique=True)),
                ('temperaturaideal', models.FloatField()),
                ('temperaturamin', models.FloatField()),
                ('temperaturamax', models.FloatField()),
                ('humedadtierraideal', models.FloatField()),
                ('humedadtierramin', models.FloatField()),
                ('humedadtierramax', models.FloatField()),
                ('humedadambienteideal', models.FloatField()),
                ('humedadambientemin', models.FloatField()),
                ('humedadambientemax', models.FloatField()),
                ('nivelagua', models.FloatField()),
                ('luz', models.BooleanField()),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
                ('habilitado', models.BooleanField()),
                ('fechacreacion', models.DateTimeField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idpermiso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrepermiso', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisoxrol',
            fields=[
                ('idrol', models.IntegerField(primary_key=True, serialize=False)),
                ('idpermiso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('idplanta', models.IntegerField(primary_key=True, serialize=False)),
                ('idtipoplanta', models.IntegerField()),
                ('idzona', models.IntegerField()),
                ('idsemilla', models.IntegerField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
                ('humedadmin', models.FloatField()),
                ('humedadideal', models.FloatField()),
                ('humedadmax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('idsemilla', models.IntegerField(primary_key=True, serialize=False)),
                ('idtipoplanta', models.IntegerField()),
                ('idmodulo', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoplanta',
            fields=[
                ('idtipoplanta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrecomun', models.CharField(max_length=255)),
                ('nombrecientifico', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipozona',
            fields=[
                ('idtipozona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('idrol', models.IntegerField()),
                ('nombres', models.CharField(max_length=255)),
                ('apellidopaterno', models.CharField(max_length=255)),
                ('apellidomaterno', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('fechanacimiento', models.DateTimeField()),
                ('nombreusuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarioxinvernadero',
            fields=[
                ('idinvernadero', models.IntegerField(primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idzona', models.IntegerField(primary_key=True, serialize=False)),
                ('idtipozona', models.IntegerField()),
                ('idinvernadero', models.IntegerField()),
                ('codigozona', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('temperaturaideal', models.FloatField()),
                ('temperaturamin', models.FloatField()),
                ('temperaturamax', models.FloatField()),
                ('fechacreacion', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
