# Generated by Django 2.0.4 on 2018-05-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('idauditoria', models.IntegerField(primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField()),
                ('tabla', models.CharField(max_length=255)),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('dataantigua', models.TextField()),
                ('datanueva', models.TextField()),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idfoto', models.IntegerField(primary_key=True, serialize=False)),
                ('idmodulo', models.IntegerField()),
                ('ruta', models.CharField(max_length=255)),
                ('nombresinextension', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('nombrefoto', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
            options={
                'db_table': 'foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiainvernadero',
            fields=[
                ('idhistoriainvernadero', models.IntegerField(primary_key=True, serialize=False)),
                ('idinvernadero', models.IntegerField()),
                ('nivelenergia', models.FloatField()),
                ('niveltanqueagua', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
            options={
                'db_table': 'historiainvernadero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiamodulo',
            fields=[
                ('idhistoriamodulo', models.IntegerField(primary_key=True, serialize=False)),
                ('idmodulo', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('humedadtierra', models.FloatField()),
                ('humedadambiente', models.FloatField()),
                ('nivelagua', models.FloatField()),
                ('concentracionco2', models.FloatField()),
                ('luz', models.BooleanField()),
                ('fecharegistro', models.DateTimeField()),
                ('comentario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'historiamodulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiaplanta',
            fields=[
                ('idhistoriaplanta', models.IntegerField(primary_key=True, serialize=False)),
                ('idplanta', models.IntegerField()),
                ('idzona', models.IntegerField()),
                ('humedad', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
            options={
                'db_table': 'historiaplanta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiasemilla',
            fields=[
                ('idhistoriasemilla', models.IntegerField(primary_key=True, serialize=False)),
                ('idsemilla', models.IntegerField()),
                ('idmodulo', models.IntegerField()),
                ('posx', models.IntegerField()),
                ('posy', models.IntegerField()),
                ('comentario', models.CharField(max_length=255)),
                ('fecharegistro', models.DateTimeField()),
            ],
            options={
                'db_table': 'historiasemilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiazona',
            fields=[
                ('idhistoriazona', models.IntegerField(primary_key=True, serialize=False)),
                ('idzona', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('ph', models.FloatField()),
                ('concentracionco2', models.FloatField()),
                ('fecharegistro', models.DateTimeField()),
            ],
            options={
                'db_table': 'historiazona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('idinvernadero', models.IntegerField(primary_key=True, serialize=False)),
                ('idadmin', models.IntegerField()),
                ('codigoinvernadero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField()),
                ('area', models.FloatField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
                ('shachacampo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'invernadero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulosemilla',
            fields=[
                ('idmodulo', models.IntegerField(primary_key=True, serialize=False)),
                ('codigomodulo', models.IntegerField(unique=True)),
                ('temperaturaideal', models.FloatField()),
                ('temperaturamin', models.FloatField()),
                ('temperaturamax', models.FloatField()),
                ('humedadtierraideal', models.FloatField()),
                ('humedadtierramin', models.FloatField()),
                ('humedadtierramax', models.FloatField()),
                ('humedadambienteideal', models.FloatField()),
                ('humedadambientemin', models.FloatField()),
                ('humedadambientemax', models.FloatField()),
                ('nivelagua', models.FloatField()),
                ('luz', models.BooleanField()),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
                ('habilitado', models.BooleanField()),
                ('fechacreacion', models.DateTimeField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulosemilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idpermiso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrepermiso', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisoxrol',
            fields=[
                ('idrol', models.IntegerField(primary_key=True, serialize=False)),
                ('idpermiso', models.IntegerField()),
            ],
            options={
                'db_table': 'permisoxrol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('idplanta', models.IntegerField(primary_key=True, serialize=False)),
                ('idtipoplanta', models.IntegerField()),
                ('idzona', models.IntegerField()),
                ('idsemilla', models.IntegerField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
                ('humedadmin', models.FloatField()),
                ('humedadideal', models.FloatField()),
                ('humedadmax', models.FloatField()),
            ],
            options={
                'db_table': 'planta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('idsemilla', models.IntegerField(primary_key=True, serialize=False)),
                ('idtipoplanta', models.IntegerField()),
                ('idmodulo', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'semilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoplanta',
            fields=[
                ('idtipoplanta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrecomun', models.CharField(max_length=255)),
                ('nombrecientifico', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
            options={
                'db_table': 'tipoplanta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipozona',
            fields=[
                ('idtipozona', models.DateTimeField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField()),
            ],
            options={
                'db_table': 'tipozona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('idrol', models.IntegerField()),
                ('nombres', models.CharField(max_length=255)),
                ('apellidopaterno', models.CharField(max_length=255)),
                ('apellidomaterno', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('fechanacimiento', models.DateTimeField()),
                ('nombreusuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarioxinvernadero',
            fields=[
                ('idinvernadero', models.IntegerField(primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarioxinvernadero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idzona', models.IntegerField(primary_key=True, serialize=False)),
                ('idtipozona', models.IntegerField()),
                ('idinvernadero', models.IntegerField()),
                ('codigozona', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('temperaturaideal', models.FloatField()),
                ('temperaturamin', models.FloatField()),
                ('temperaturamax', models.FloatField()),
                ('fechacreacion', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
                ('idusuarioauditado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
