# Generated by Django 2.0.4 on 2018-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180523_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='sachadata',
            field=models.CharField(default='sachadata', max_length=255),
        ),
        migrations.AlterModelTable(
            name='auditoria',
            table=None,
        ),
    ]
