# Generated by Django 2.0.4 on 2018-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='concentracionco2ideal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zona',
            name='concentracionco2max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zona',
            name='concentracionco2min',
            field=models.FloatField(default=0),
        ),
    ]
