# Generated by Django 2.0.4 on 2018-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180527_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='concentracionco2ideal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='zona',
            name='concentracionco2max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='zona',
            name='concentracionco2min',
            field=models.FloatField(),
        ),
    ]
