# Generated by Django 2.0.4 on 2018-05-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180523_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='sachadata',
        ),
    ]
