# Generated by Django 2.0.4 on 2018-05-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_auditoria_sachadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'managed': False},
        ),
    ]
