# Generated by Django 2.0.4 on 2018-05-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180527_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
