# Generated by Django 2.0.4 on 2018-05-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180523_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'managed': False},
        ),
    ]
