# Generated by Django 2.0.4 on 2018-05-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auditoria_sachanuevocampo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiainvernadero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiamodulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiaplanta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiasemilla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiazona',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invernadero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modulosemilla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permisoxrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semilla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipozona',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarioxinvernadero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={},
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='sachanuevocampo',
        ),
    ]
