# Generated by Django 2.0.4 on 2018-05-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180523_1044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historiainvernadero',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historiamodulo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historiaplanta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historiasemilla',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historiazona',
            table=None,
        ),
        migrations.AlterModelTable(
            name='invernadero',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modulosemilla',
            table=None,
        ),
        migrations.AlterModelTable(
            name='permiso',
            table=None,
        ),
        migrations.AlterModelTable(
            name='permisoxrol',
            table=None,
        ),
        migrations.AlterModelTable(
            name='planta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rol',
            table=None,
        ),
        migrations.AlterModelTable(
            name='semilla',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipozona',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuarioxinvernadero',
            table=None,
        ),
        migrations.AlterModelTable(
            name='zona',
            table=None,
        ),
    ]
