# Generated by Django 2.0.4 on 2018-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180523_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='semilla',
            name='nombrecientificonuevo',
            field=models.CharField(default='def', max_length=255),
        ),
    ]
