# Generated by Django 2.0.4 on 2018-05-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_semilla_nombrecientificonuevo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoplanta',
            options={},
        ),
    ]
