# Generated by Django 2.0.4 on 2018-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180523_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplanta',
            name='nombrecientificonuevo',
            field=models.CharField(default='sacha', max_length=255),
        ),
        migrations.AlterModelTable(
            name='tipoplanta',
            table=None,
        ),
    ]
