# Generated by Django 2.0.4 on 2018-05-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180523_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semilla',
            name='nombrecientificonuevo',
        ),
        migrations.RemoveField(
            model_name='tipoplanta',
            name='nombrecientificonuevo',
        ),
    ]
