INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (1, 'Ver Invernadero', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (2, 'Crear Invernadero', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (3, 'Editar Invernadero', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (4, 'Eliminar Invernadero', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (5, 'Ver Usuario', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (6, 'Crear Usuario', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (7, 'Editar Usuario', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (8, 'Eliminar Usuario', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (9, 'Ver Zona', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (10, 'Crear Zona', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (11, 'Editar Zona', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (12, 'Eliminar Zona', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (13, 'Ver Panelluz', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (14, 'Crear Panelluz', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (15, 'Editar Panelluz', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (16, 'Eliminar Panelluz', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (17, 'Ver Modulosemilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (18, 'Crear Modulosemilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (19, 'Editar Modulosemilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (20, 'Eliminar Modulosemilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (21, 'Ver Semilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (22, 'Crear Semilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (23, 'Editar Semilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (24, 'Eliminar Semilla', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (25, 'Ver Planta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (26, 'Crear Planta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (27, 'Editar Planta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (28, 'Eliminar Planta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (29, 'Ver Tipoplanta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (30, 'Crear Tipoplanta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (31, 'Editar Tipoplanta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (32, 'Eliminar Tipoplanta', true);
INSERT INTO public.app_permiso (idpermiso, nombrepermiso, habilitado) VALUES (33, 'Ver Estadistica', true);

INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 1);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 2);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 3);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 4);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 5);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 6);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 7);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 8);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 9);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 10);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 11);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 12);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 13);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 14);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 15);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 16);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 17);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 18);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 19);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 20);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 21);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 22);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 23);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 24);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 25);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 26);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 27);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 28);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 29);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 30);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 31);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 32);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (-1, 33);

INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 1);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 2);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 3);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 4);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 5);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 6);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 7);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 8);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 9);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 10);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 11);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 12);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 13);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 14);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 15);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 16);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 17);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 18);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 19);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 20);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 21);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 22);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 23);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 24);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 25);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 26);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 27);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 28);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 29);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 30);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 31);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 32);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (1, 33);

INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 1);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 9);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 13);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 17);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 21);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 25);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 29);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (3, 33);

INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 1);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 9);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 10);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 11);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 13);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 14);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 15);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 17);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 18);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 19);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 21);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 22);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 23);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 25);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 26);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 27);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 29);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 30);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 31);
INSERT INTO public.app_permisoxrol(idrol, idpermiso) VALUES (2, 33);